
import React from 'react';
import { SocialMediaPackData } from '../types';
import { BRAND_INFO } from '../constants';
import { PlatformIcon } from '../components/PlatformIcons';

const SocialMediaPackPreview: React.FC<{ data: SocialMediaPackData }> = ({ data }) => {
  return (
    <div className="bg-gray-50 text-[#333333] font-['Open_Sans'] p-8" style={{ fontFamily: BRAND_INFO.typography.body }}>
      <div className="max-w-4xl mx-auto">
        <header className="text-center mb-10">
          <h1 style={{ fontFamily: BRAND_INFO.typography.headings, color: BRAND_INFO.colors.primaryBlue }} className="text-3xl font-bold mb-2">Social Media Campaign</h1>
          <p className="text-xl text-gray-700">{data.campaignTitle}</p>
        </header>

        <main className="space-y-6">
          {data.posts.map((post, index) => (
            <div key={index} className="bg-white rounded-lg shadow-md border border-gray-200 overflow-hidden">
              <div className="p-5 flex items-center border-b bg-white">
                 <PlatformIcon platform={post.platform} className="w-8 h-8 mr-4" style={{color: BRAND_INFO.colors.primaryBlue}}/>
                 <h2 className="text-lg font-bold" style={{ color: BRAND_INFO.colors.textDark }}>{post.platform} Post</h2>
              </div>
              <div className="p-5 grid md:grid-cols-2 gap-5">
                <div>
                  <h3 className="font-bold text-md mb-2 text-gray-600">Caption:</h3>
                  <p className="text-sm text-gray-800 whitespace-pre-wrap">{post.caption}</p>
                </div>
                <div className="bg-gray-100 p-4 rounded-md border">
                   <h3 className="font-bold text-md mb-2 text-gray-600">Image Suggestion:</h3>
                   <p className="text-sm text-gray-800 italic">{post.imageSuggestion}</p>
                </div>
              </div>
            </div>
          ))}
        </main>

        <footer className="text-center text-xs text-gray-500 mt-12">
          <p>Generated by {BRAND_INFO.name} Brand Studio</p>
        </footer>
      </div>
    </div>
  );
};

export default SocialMediaPackPreview;
